### PR TITLE
Complete Overhaul

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>

Please check the **[Preview]**.

<br>

### Changes

- API changes:
  `app` -> `with`
  `opn` -> `open`
- Changed recommended url to module to:
  `https://github.com/hashrock/deno-opn/raw/master/mod.ts`
  the now standard way of import github modules
- Sorted files into:
  - `Documentation`
  - `Source`
  - `Tools`
- Added basic test script
  (not unit tests, could be added in another PR)
- Separated code into topic specific files
- Separated code into internal js and wrapping ts
- Fixed file names `license` -> `LICENSE` ,..
- Made default entry point `mod.ts` to keep it standard
- Formatted README
- Added badges for license, project & port
- Added legacy compatibility wrapper + test

*Please ask me if you have questions regarding the code,*
*you seem to have 'misused' some features like declaring*
*the main function async when you were returning a promise,*
*of course they could be switched over to actually use async,*
*which is the nicer way anyways~*

*Changing API / access point to a library is generally not great,*
*but considering that this library hadn't been updated and Deno*
*creates local versions of the imported modules it actually isn't*
*much of a problem I'd say.*

*With the `mod.ts` / wrapper approach it is now actually free to*
*change internally in terms of file structure.*

<br>

### Repository Suggestions

- Add tags

- Disable unused widgets:

  - `Packages`

- Disable unused tabs:

  - `Projects`

  - `Actions`

  - `Wiki`

### Still Working On

- ~~README~~

[Preview]: https://github.com/ElectronicsArchiver/deno-opn

### CODE REVIEW

**Comment by hashrock** [comment]
Thank you! You've made the code very structured and better.

I would like to keep API changes to a minimum, but what is the reason for the "app -> with" change?

**Comment by hashrock** [comment]
Great! I am learning quite a bit thanks to you.

image

It seems like there is almost few traffic. it looks like no one is in that much trouble with Breaking change.
But I might just try to have `opt.ts` as backward compatibility like you said. This is not only for this repository, but as an exercise for my future libraries.

**Comment by ElectronicsArchiver** [comment]
Great! I am learning quite a bit thanks to you. <3

> It seems like there is almost few traffic. it looks like no one is in that much trouble with Breaking change.
But I might just try to have opt.ts as backward compatibility like you said. This is not only for this repository, but as an exercise for my future libraries.

Actually I already finished it, I'll add it~

**Comment by hashrock** [comment]
Great! Thank you!

**Pull request merged**
